language: node_js
dist: trusty
node_js:
- '13'
- '12'
matrix:
  allow_failures:
    - node_js: '13'
services:
- mysql
- postgresql
env:
- MYSQL_PORT=3306 POSTGRESQL_PORT=5432
before_install:
- sudo pip install -U urllib3 requests
- sudo pip install futoin-cid
- sudo bash test/db_config.sh
script:
- rm -rf node_modules
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid prepare
- nodeVer=$TRAVIS_NODE_VERSION nodeEnv=development cid run test

